### ISSUE TITLE
BaseUrl is null at DeviceFactory.CreateDeviceAsync (IPAddress)

### ISSUE THREAD

**Issue by KalleStae** [inflames2k/PS.FritzBox.API#26]
The creation of the Fritzbox device differs between CreateDeviceAsync (IPAddress) and LocateDevicesAsync ().
 Is it wanted like that ??

**Comment by inflames2k** [comment]
Hello,

the main reason is that these are two fundamentally different approaches.

With the DeviceLocator and the related functionalities the network is searched for all responding devices and on this basis the FritzDevice instance is formed.

All this is not mapped at all via the CreateDeviceAsync method. However, the factory has unfortunately been completely overlooked in the latest adjustments as well.

When the opportunity arises, this will be fixed. However, I don't see that it has a particularly high priority at the moment.

I hope this is OK. Otherwise you are of course free to open a pullrequest, which will be taken over into the code after checking.

**Comment by KalleStae** [comment]
For me that's ok, but I think the time differences to create a Fritzbox are quite large depending on the network. so it would be good if you can do it via the ip. Especially if you only have one Fritzbox in the network. In addition, when creating via the Ip, the BaseUrl must be supplied for each service client. Just as a suggestion for a next release.
